/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Link, Node } from "./components/bubbles-ui/bubbles-ui.types";
export { Link, Node } from "./components/bubbles-ui/bubbles-ui.types";
export namespace Components {
    interface BubbleCard {
        "description"?: HTMLElement;
        "icon"?: HTMLElement;
        "name"?: HTMLElement;
    }
    interface BubblesUi {
        /**
          * The center of the force graph
         */
        "center"?: { x?: number, y?: number };
        /**
          * The links between the force graph nodes
         */
        "links"?: Link[];
        /**
          * The nodes composing the force graph
         */
        "nodes"?: Node[];
    }
}
declare global {
    interface HTMLBubbleCardElement extends Components.BubbleCard, HTMLStencilElement {
    }
    var HTMLBubbleCardElement: {
        prototype: HTMLBubbleCardElement;
        new (): HTMLBubbleCardElement;
    };
    interface HTMLBubblesUiElement extends Components.BubblesUi, HTMLStencilElement {
    }
    var HTMLBubblesUiElement: {
        prototype: HTMLBubblesUiElement;
        new (): HTMLBubblesUiElement;
    };
    interface HTMLElementTagNameMap {
        "bubble-card": HTMLBubbleCardElement;
        "bubbles-ui": HTMLBubblesUiElement;
    }
}
declare namespace LocalJSX {
    interface BubbleCard {
        "description"?: HTMLElement;
        "icon"?: HTMLElement;
        "name"?: HTMLElement;
    }
    interface BubblesUi {
        /**
          * The center of the force graph
         */
        "center"?: { x?: number, y?: number };
        /**
          * The links between the force graph nodes
         */
        "links"?: Link[];
        /**
          * The nodes composing the force graph
         */
        "nodes"?: Node[];
    }
    interface IntrinsicElements {
        "bubble-card": BubbleCard;
        "bubbles-ui": BubblesUi;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bubble-card": LocalJSX.BubbleCard & JSXBase.HTMLAttributes<HTMLBubbleCardElement>;
            "bubbles-ui": LocalJSX.BubblesUi & JSXBase.HTMLAttributes<HTMLBubblesUiElement>;
        }
    }
}
