/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Link, Node } from "./components/bubbles-ui/bubbles-ui.types";
export { Link, Node } from "./components/bubbles-ui/bubbles-ui.types";
export namespace Components {
    interface BubblesUi {
        /**
          * The data nodes passed to the force graph
         */
        "data"?: {
    nodes?: Node[],
    links?: Link[]
  };
    }
}
declare global {
    interface HTMLBubblesUiElement extends Components.BubblesUi, HTMLStencilElement {
    }
    var HTMLBubblesUiElement: {
        prototype: HTMLBubblesUiElement;
        new (): HTMLBubblesUiElement;
    };
    interface HTMLElementTagNameMap {
        "bubbles-ui": HTMLBubblesUiElement;
    }
}
declare namespace LocalJSX {
    interface BubblesUi {
        /**
          * The data nodes passed to the force graph
         */
        "data"?: {
    nodes?: Node[],
    links?: Link[]
  };
    }
    interface IntrinsicElements {
        "bubbles-ui": BubblesUi;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bubbles-ui": LocalJSX.BubblesUi & JSXBase.HTMLAttributes<HTMLBubblesUiElement>;
        }
    }
}
